package org.featherlessbipeds.utils;

public enum ClientFlag
{
    EDIT_PROFILE_INVALID_EMAIL,
    EDIT_PROFILE_EMPTY_EMAIL,
    EDIT_PROFILE_EMPTY_SURNAME,
    EDIT_PROFILE_EMPTY_CEP,
    EDIT_PROFILE_EMPTY_NAME,
    EDIT_PROFILE_EMAIL_CONFLICT,
    EDIT_PROFILE_ERROR
}
