package org.featherlessbipeds.utils;

public enum OrderServiceFlag {

    ORDER_BUDGET_INVALID,
    ORDER_TERM_INVALID,
    ORDER_ATTACHMENT_FORMAT_INVALID,
    ORDER_DESCRIPTION_EMPTY,
    ORDER_SERVICE_CATEGORY_EMPTY,
    ORDER_LOCATION_INVALID,
    ORDER_LOCATION_MISMATCH

}
