package org.featherlessbipeds.utils;

public enum UserFlag
{
    GOOGLE_LOGIN_ERROR,
    FACEBOOK_LOGIN_ERROR,
    CHANGE_PASSWORD_INVALID_TOKEN,
    CHANGE_PASSWORD_INVALID_CONFIRM,
    CHANGE_PASSWORD_USER_NOT_FOUND,
    CHANGE_PASSWORD_ERROR,
    LOGIN_ERROR
}
